-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 18:40:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydbRoberto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydbRoberto` ;

-- -----------------------------------------------------
-- Schema mydbRoberto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydbRoberto` DEFAULT CHARACTER SET utf8 ;
USE `mydbRoberto` ;

-- -----------------------------------------------------
-- Table `mydbRoberto`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbRoberto`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydbRoberto`.`CLIENTE` (
  `dni` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fechaNac` DATETIME NOT NULL,
  `tlfn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbRoberto`.`PROVEEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbRoberto`.`PROVEEDOR` ;

CREATE TABLE IF NOT EXISTS `mydbRoberto`.`PROVEEDOR` (
  `nif` CHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbRoberto`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbRoberto`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `mydbRoberto`.`PRODUCTO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL NOT NULL DEFAULT 0,
  `PROVEEDOR_nif` CHAR(9) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_PRODUCTO_PROVEEDOR1_idx` (`PROVEEDOR_nif` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_nif`)
    REFERENCES `mydbRoberto`.`PROVEEDOR` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydbRoberto`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydbRoberto`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `mydbRoberto`.`COMPRA` (
  `CLIENTE_dni` CHAR(9) NOT NULL,
  `PRODUCTO_codigo` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_dni`, `PRODUCTO_codigo`),
  INDEX `fk_COMPRA_CLIENTE_idx` (`CLIENTE_dni` ASC) VISIBLE,
  INDEX `fk_COMPRA_PRODUCTO1_idx` (`PRODUCTO_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_CLIENTE`
    FOREIGN KEY (`CLIENTE_dni`)
    REFERENCES `mydbRoberto`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo`)
    REFERENCES `mydbRoberto`.`PRODUCTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
